[general]
filename = ./frames.cxi
i0 = 0
n_images = 2000
output_level = 5

[raw]
cmcx = False
cmcy = False
dataset_name = /entry_1/data_1/data
saturation_level = 50000
skip_saturated_frames = True
subtract_constant = 0
xmax = 2000
xmin = 1100
ymax = 550
ymin = 200

[process]
cmcx = False
cmcy = False
dataset_name = /entry_1/image_1/data
floor_cut_level = 0
subtract_constant = 0

[denoise]
method = gauss
sigma = 0.1

[threshold]
fill_holes = False
threshold = 20.0

[detect]
min_dist = 0.0
n_particles_max = 2
peak_centering = center_of_mass

[analyse]
circle_window = True
integration_mode = windows
window_size = 25
